### ISSUE TITLE
Versão mínima do PHP

### ISSUE THREAD

**Issue by geekcom** [lpj145/FiremonPHP#1]
Qual é a versão mínima do PHP para essa lib?
Não vi isso no seu composer.json

**Comment by lpj145** [comment]
desculpa por isso, desenvolvi com php 7.1 mas acredito que com o 5.6 funcione corretamente, afinal, não existe nenhuma feature tão nova nela.

**Comment by lpj145** [comment]
vale lembrar que essa lib esta sendo reescrita, pois a class Database não soube o que fazer com a leitura, apenas com a escrita, então esta sendo tudo refatorado novamente, e o projeto de englobar todo o resto da arquitetura, sendo assim sera aberto um novo repositório FiremonPHP/Database.

**Comment by geekcom** [comment]
Muito boa a iniciativa @lpj145 , parabéns
